globals={
    'hs',
    'table.keys',
    'table.append',
    'table.ifind',
    'table.find',
    'table.each',
    'table.ieach',
    'table.filter',
    'table.map',
    'table.imap',
    'table.shallow_copy',
    'table.deep_copy',
    'table.compact',
    'table.tostring',
    'toarray'
}
